### ISSUE TITLE
Display scrollbar when there are too many tabs

### ISSUE THREAD

**Issue by Pauan** [tiger4th/vertical-tabs#7]
This package is really fantastic! ...until you have so many tabs that it can't display all of them. In that case all the "excess" tabs get cut off and are inaccessible.

I don't know much about Atom package development, but maybe it's as simple as setting `overflow: auto`?

**Comment by a7madgamal** [comment]
+1

**Comment by tiger4th** [comment]
I'm glad you like it.
I fixed the issue at version 0.4.3.

**Comment by Pauan** [comment]
Thanks! I'm using `0.4.3` now, and the scrollbar still doesn't show up, but it's now possible to scroll the list using the mousewheel, so that's an improvement. I'm not sure if Atom even allows you to display a scrollbar in the tabs.

**Comment by maxdelorme** [comment]
.tab-bar::-webkit-scrollbar {
  display:unset !important;
}

**Comment by tiger4th** [comment]
@maxdelorme Thanks!
